name: auto-clang-format
on: [push, pull_request]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: true
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.event.pull_request.head.ref }}
        
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: '.'
        exclude: './third_party ./external'
        extensions: 'h,cpp,hpp'
        clangFormatVersion: 12
        inplace: True
        
    - uses: EndBug/add-and-commit@v9
      with:
        add: "."
        author_name: Clang Robot
        author_email: robot@cleanup.com
        message: ':art: Committing clang-format changes'
        push: true
